sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 200681600Zjn
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7525kL3WuhZjWKREvq
    access-key-secret: EN2IkVTXjLHSL0J4XIsMqMnok3TVJc
    bucket-name: java-nik
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxee3344ad71a9f41a
    secret: 448265f84eafd8c76b5ee9e65e6d02ca